plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
remote_theme: "pages-themes/primer"
title: COVID-19, Sicilia - Un progetto di OpenDataSicilia
description: Visualizzazioni di base, per la Sicilia
